#!/bin/sh
if [ "$#" -ne 0 ];
  then echo "usage: create"
  exit 1
fi

aws cloudformation create-stack \
  --stack-name ttrssal2 \
  --template-body file://ttrss.yaml \
  --capabilities CAPABILITY_IAM     \
  --parameters ParameterKey=SshSecurityGroup,ParameterValue=sg-0bb841b5f19ace45e
