#!/bin/sh
if [ "$#" -ne 5 ];
  then echo "usage: update dbuser dbpass dbrootpass domain email"
  exit 1
fi

aws cloudformation update-stack \
  --stack-name ttrss \
  --template-body file://ttrss.yaml \
  --capabilities CAPABILITY_IAM \
  --parameters ParameterKey=DBUser,ParameterValue=$1 \
               ParameterKey=DBPass,ParameterValue=$2 \
               ParameterKey=DBRootPass,ParameterValue=$3 \
               ParameterKey=Domain,ParameterValue=$4 \
               ParameterKey=Email,ParameterValue=$5
