#!/bin/sh

user=${1:-"dbuserreplaceme"}
host=${2:-"dbhostreplaceme"}
pass=${3:-"dbpassreplaceme"}
updater=${3:-"containernamereplaceme"}
s3location=${4:-"s3locationreplaceme"}

podman stop "$updater"
echo "Stopped container $updater"
# Sleeping shouldn't need to be done since we're not planning on the
# multi-process updater
# Sleep 60 seconds as the updater spawns processes sometimes. This will let them settle out.
# sleep 60
echo "Backing up DB"

# Run the dump. Note the redirection is to podman exec,
# not mysqldump, so the output will come to the host and the
# redirection is therefore to a file on the host
podman exec "$host"            \
  mysqldump -u "$user"         \
  -h "$host"                   \
  --password="${pass}"         \
  --opt ttrss > ttrss.sql

gzip -f ttrss.sql

[ "$(du -k ttrss.sql.gz | cut -f 1)" -ge 6000 ] && \
   aws s3 cp ttrss.sql.gz s3://"${s3location}"

echo "Starting updater"
podman start "$updater"
