#!/bin/sh

user=${1:-"dbuserreplaceme"}
host=${2:-"dbhostreplaceme"}
pass=${3:-"dbpassreplaceme"}
updater=${3:-"containernamereplaceme"}
dir=$(dirname "$(readlink -f -- "$0")") # GNU readlink - Linux only

podman stop "$updater"
echo "Stopped container $updater"
# Sleep 60 seconds as the updater spawns processes sometimes. This will let them settle out.
sleep 60
echo "Cleaning DB"

# Delete unused data
podman exec "$host"            \
  mysql --user="$user"         \
  --password="${pass}"         \
  -h "$host"                   \
  ttrss < "$dir"/maintain.sql

# Optimize the db
podman exec "$host"                                     \
  mysqlcheck -u "$user" --password="${pass}" -h "$host" \
  --optimize --databases ttrss

echo "Starting updater"
podman start "$updater"
