#!/bin/sh

user=${1:-"dbuserreplaceme"}
host=${2:-"dbhostreplaceme"}
pass=${3:-"dbpassreplaceme"}

# Determine the pod PID. That spawns a systemd process, which spawns our
# updater. So we are looking for a child of the child of our pod pid, which
# will be a php process
pod_pid=$(ps -uax |grep -F $(rkt list |grep -F running |grep -F ttrss-update-daemon |cut -f 1) | awk '{print $2}')
updater_pid=$(pgrep -P $(pgrep -P "$pod_pid") php)
kill -s STOP "$updater_pid"
echo "Stopped PID $updater_pid"
# Sleep 60 seconds as the updater spawns processes sometimes. This will let them settle out.
sleep 60
echo "Cleaning DB"

# Delete unused data
mysql --user="$user"           \
  --password="${pass}"         \
  -h "$host"                   \
  ttrss < maintain.sql

# Optimize the db
mysqlcheck -u "$user" --password="${pass}" -h "$host" \
  --optimize --databases ttrss

echo "Starting updater"
kill -s CONT "$updater_pid"
