#!/bin/sh
git clone --depth 1 https://git.tt-rss.org/fox/tt-rss.git "$1"

# TT-RSS permissions: Note that in testing, cache/js did not exist, but that's ok here
(cd "$1" && \
  chmod -R 777 cache/images \
               cache/upload \
               cache/export \
               cache/js \
               feed-icons \
               lock
)
