#!/bin/sh

if [ $# -lt 2 ]; then
  echo "usage: start-mariadb root-password image-name [network] [container-name]" >&2
  exit 1
fi

DBRootPass=${1}
image="$2"
network=${3:-ttrss}
name=${4:-ttrss-mariadb}

dir=$(dirname "$(readlink -f -- "$0")") # GNU readlink - Linux only

# syntax reminder
# -v host:container
podman run -d                             \
  -e MYSQL_ROOT_PASSWORD="$DBRootPass"    \
  --network "$network"                    \
  --name "$name"                          \
  -v /data:/var/lib/mysql                 \
  -v "$dir"/mariadb:/etc/mysql/conf.d:ro \
  "$image"
