#!/bin/sh

update=$(rkt prepare                             \
  --net=host                                     \
  --volume ttrss,kind=host,source=/var/tt-rss    \
  --mount volume=ttrss,target=/var/ttrss         \
  --dns=host                                     \
  docker://elerch/ttrss-update-daemon)
nohup rkt run-prepared $update > /output/updater.out &

echo $nginx
