#!/bin/sh

if [ $# -lt 1 ]; then
  echo "usage: start-updates image-name [network] [container-name]" >&2
  exit 1
fi

image="$1"
network=${2:-ttrss}
name=${3:-ttrss-updater}

# syntax reminder
# -v host:container
podman run -d                    \
  --restart=always               \
  --network "$network"           \
  --name "$name"                 \
  -e MULTIPROCESS=0              \
  -v /var/tt-rss:/var/tt-rss     \
  "$image"
