#!/bin/sh

update=$(rkt prepare                             \
  --volume ttrss,kind=host,source=/var/tt-rss    \
  --mount volume=ttrss,target=/var/ttrss         \
  docker://elerch/ttrss-update-daemon)

nohup rkt run-prepared --net=host --dns=host $update > /output/updater.out &

echo $update
