#!/bin/sh

if [ $# -lt 2 ]; then
  echo "usage: start-nginx image-name [network] [container-name]" >&2
  exit 1
fi

image="$1"
network=${2:-ttrss}
name=${3:-ttrss-nginx}
dir=$(dirname "$(readlink -f -- "$0")") # GNU readlink - Linux only

[ ! -f "$dir"/dhparam.pem ] &&                         \
  time openssl dhparam -out "$dir"/dhparam.pem 2048

podman run -d                                                \
  --network "$network"                                       \
  --name "$name"                                             \
  -p 443:443                                                 \
  -v /var/tt-rss:/usr/share/nginx/html:ro                    \
  -v "$dir"/nginx:/etc/nginx/conf.d:ro                       \
  -v "$dir"/dhparam.pem:/etc/nginx/dhparam/dhparam.pem:ro    \
  "$image"
